# Generated by Django 5.0.2 on 2024-02-14 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('index', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_municipio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('index', models.BigAutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_uf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('index', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='federacao.municipio')),
            ],
            options={
                'db_table': 'tb_bairro',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='municipio',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='federacao.uf'),
        ),
    ]
